In [33]:
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
# Step 1: Load the sheets into DataFrames
df1 = pd.read_csv('/Genomics/pritykinlab/yujie/preprocessing_benchmarking/snakemake_results/preprocessing_scores/all.tsv', sep='\t')  
df2 = pd.read_csv('/Genomics/pritykinlab/yujie/preprocessing_benchmarking/new_results/aggregated_results.tsv', sep='\t')

In [35]:
df1

,num_PCs,label,neighbors_count,HVG_method,num_HVG,norm_method
0,10,AAAS,1.000000,seurat,2000,log_zscore
1,10,AAMP,1.000000,seurat,2000,log_zscore
2,10,AARS,1.000000,seurat,2000,log_zscore
3,10,AARS2,1.000000,seurat,2000,log_zscore
4,10,AASDHPPT,1.000000,seurat,2000,log_zscore
...,...,...,...,...,...,...
32523,25,ZRANB2,1.000000,cell_ranger,3000,pearson_residuals
32524,25,ZRSR2,1.000000,cell_ranger,3000,pearson_residuals
32525,25,ZW10,1.000000,cell_ranger,3000,pearson_residuals
32526,25,ZWINT,1.000000,cell_ranger,3000,pearson_residuals
32527,25,non-targeting,1.817834,cell_ranger,3000,pearson_residuals

In [36]:
df2

,num_PCs,label,neighbors_count,hvg_method,num_hvg,norm_method,max_pcs,label_col,num_nn,num_pcs_list
0,10,AAAS,1.000000,seurat,2000,log_zscore,25,gene,20,10
1,10,AAMP,1.000000,seurat,2000,log_zscore,25,gene,20,10
2,10,AARS,1.000000,seurat,2000,log_zscore,25,gene,20,10
3,10,AARS2,1.000000,seurat,2000,log_zscore,25,gene,20,10
4,10,AASDHPPT,1.000000,seurat,2000,log_zscore,25,gene,20,10
...,...,...,...,...,...,...,...,...,...,...
32523,25,ZRANB2,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32524,25,ZRSR2,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32525,25,ZW10,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32526,25,ZWINT,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32527,25,non-targeting,1.817834,cell_ranger,3000,pearson_residuals,25,gene,20,25

In [37]:
# Rename 'neighbors_count' in df2 to avoid column name collision during merge
df2.rename(columns={'neighbors_count': 'neighbors_count_new_pipeline'}, inplace=True)

df2.rename(columns={'num_hvg': 'num_HVG'}, inplace=True)
df2.rename(columns={'hvg_method': 'HVG_method'}, inplace=True)

In [38]:
df2

,num_PCs,label,neighbors_count_new_pipeline,HVG_method,num_HVG,norm_method,max_pcs,label_col,num_nn,num_pcs_list
0,10,AAAS,1.000000,seurat,2000,log_zscore,25,gene,20,10
1,10,AAMP,1.000000,seurat,2000,log_zscore,25,gene,20,10
2,10,AARS,1.000000,seurat,2000,log_zscore,25,gene,20,10
3,10,AARS2,1.000000,seurat,2000,log_zscore,25,gene,20,10
4,10,AASDHPPT,1.000000,seurat,2000,log_zscore,25,gene,20,10
...,...,...,...,...,...,...,...,...,...,...
32523,25,ZRANB2,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32524,25,ZRSR2,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32525,25,ZW10,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32526,25,ZWINT,1.000000,cell_ranger,3000,pearson_residuals,25,gene,20,25
32527,25,non-targeting,1.817834,cell_ranger,3000,pearson_residuals,25,gene,20,25

In [39]:
print("Columns in df1:", df1.columns.tolist())
print("Columns in df2:", df2.columns.tolist())

Columns in df1: ['num_PCs', 'label', 'neighbors_count', 'HVG_method', 'num_HVG', 'norm_method']
Columns in df2: ['num_PCs', 'label', 'neighbors_count_new_pipeline', 'HVG_method', 'num_HVG', 'norm_method', 'max_pcs', 'label_col', 'num_nn', 'num_pcs_list']

In [40]:
# Step 2: Merge the DataFrames on the matching columns
merge_cols = ["num_PCs", "label", "HVG_method", "num_HVG", "norm_method"]
merged_df = pd.merge(df1, df2, on=merge_cols)

In [41]:
merged_df

,num_PCs,label,neighbors_count,HVG_method,num_HVG,norm_method,neighbors_count_new_pipeline,max_pcs,label_col,num_nn,num_pcs_list
0,10,AAAS,1.000000,seurat,2000,log_zscore,1.000000,25,gene,20,10
1,10,AAMP,1.000000,seurat,2000,log_zscore,1.000000,25,gene,20,10
2,10,AARS,1.000000,seurat,2000,log_zscore,1.000000,25,gene,20,10
3,10,AARS2,1.000000,seurat,2000,log_zscore,1.000000,25,gene,20,10
4,10,AASDHPPT,1.000000,seurat,2000,log_zscore,1.000000,25,gene,20,10
...,...,...,...,...,...,...,...,...,...,...,...
32523,25,ZRANB2,1.000000,cell_ranger,3000,pearson_residuals,1.000000,25,gene,20,25
32524,25,ZRSR2,1.000000,cell_ranger,3000,pearson_residuals,1.000000,25,gene,20,25
32525,25,ZW10,1.000000,cell_ranger,3000,pearson_residuals,1.000000,25,gene,20,25
32526,25,ZWINT,1.000000,cell_ranger,3000,pearson_residuals,1.000000,25,gene,20,25
32527,25,non-targeting,1.817834,cell_ranger,3000,pearson_residuals,1.817834,25,gene,20,25

In [ ]:
# Step 3: Plot the correlation
plt.figure(figsize=(10, 6))
plt.scatter(merged_df['neighbors_count'], merged_df['neighbors_count_new_pipeline'], alpha=0.6)
plt.title('Correlation of Neighbors Count between snakemake and new pipeline')
plt.xlabel('Neighbors Count (snakemake)')
plt.ylabel('Neighbors Count (new pipeline)')

# Optionally, you can compute the correlation coefficient
correlation_coefficient = merged_df['neighbors_count'].corr(merged_df['neighbors_count_new_pipeline'])
plt.annotate(f'Correlation Coefficient: {correlation_coefficient:.2f}', xy=(0.05, 0.95), xycoords='axes fraction')

plt.show()